apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-code
  namespace: {{ .Values.pipeline.namespace }}
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  type: git
  params:
  - name: url
    value: {{ .Values.pipelineresource.mainsourcecode }}
  - name: revision
    value: {{ .Values.pipelineresource.mainbranch }}
  - name: sslVerify
    value: "false"
